name: Build & Deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  BuildAndDeploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@master
    - name: Build the site
      run: .github/scripts/github/build.bash
    # - name: Deploy
    #   uses: JamesIves/github-pages-deploy-action@4.0.0
    #   with:
    #     branch: gh-pages
    #     folder: public
    #     single-commit: true
