name: Build & Deploy

on:
  push:
    branches:
      - master

jobs:
  BuildAndDeploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@master
    - name: Download Zola
      run: |
        wget https://github.com/getzola/zola/releases/download/v0.13.0/zola-v0.13.0-x86_64-unknown-linux-gnu.tar.gz
        tar -xf zola-* zola && rm zola-*
    - name: Download minify
      run: |
        wget https://github.com/tdewolff/minify/releases/download/v2.9.16/minify_linux_amd64.tar.gz
        tar -xf minify_* minify && rm minify_*
    - name: Download minify-html
      run: |
        wget https://wilsonl.in/minify-html/bin/0.4.10-linux-x86_64
        mv *linux-x86_64 minify-html
        sudo chmod u+x minify-html
    - name: Build & Minify
      run: |
        ./zola build
        for file in `find public -name "*.html" -type f`; do
          ./minify-html -s "$file" -o "$file" --css --js
        done
        ./minify -rav -o . public
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.0.0
      with:
        branch: gh-pages
        folder: public
        single-commit: true
