name: Build & Deploy

on:
  push:
    branches:
      - master

jobs:
  BuildAndDeploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@master
    - name: Download Zola
      run: |
        wget https://github.com/getzola/zola/releases/download/v0.13.0/zola-v0.13.0-x86_64-unknown-linux-gnu.tar.gz
        tar -xf zola-* zola && rm zola-*
    - name: Download minify
      run: |
        wget https://github.com/tdewolff/minify/releases/download/v2.9.12/minify_linux_amd64.tar.gz
        tar -xf minify_* minify && rm minify_*
    - name: Build & Minify
      run: |
        ./zola build
        ./minify -r -a -o public/ public
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: gh-pages
          folder: public
          single-commit: true
